/*
  # Add September 14, 2025 Daily Horoscope Data

  1. New Data
    - Daily horoscopes for all zodiac signs and cusp combinations
    - Both Northern and Southern Hemisphere content
    - Date: 2025-09-14
    - Includes daily_horoscope, affirmation, deeper_insight, mystic_opening, and monthly_forecast

  2. Content Structure
    - Hemisphere-specific seasonal guidance
    - Sign-specific energy and themes
    - Cusp-specific dual-energy content including mystic_opening
    - Premium content for subscribers
*/

-- Insert September 14, 2025 horoscope data for all signs and hemispheres

-- Pure Signs - Northern Hemisphere
INSERT INTO horoscope_cache (date, sign, hemisphere, daily_horoscope, affirmation, deeper_insight, monthly_forecast, expires_at) VALUES
('2025-09-14', 'Aries', 'Northern', 'The autumn fire within you burns with purpose — channel it into meaningful action.', 'I lead with courage and wisdom.', 'Your pioneering spirit finds new direction as seasons shift. Trust your instincts to guide you toward opportunities that align with your authentic self.', 'September brings transformation and new beginnings for Aries. The autumn equinox marks a powerful time for balancing action with reflection. Career opportunities emerge through bold leadership.', '2025-10-14'),

('2025-09-14', 'Taurus', 'Northern', 'Ground yourself in autumn''s abundance — your steady nature creates lasting beauty.', 'I build with patience and purpose.', 'The harvest season reminds you that slow, steady growth creates the most enduring results. Your practical wisdom guides others toward stability.', 'September offers Taurus a time of reaping what you''ve sown. Your patient efforts throughout the year begin to show tangible results.', '2025-10-14'),

('2025-09-14', 'Gemini', 'Northern', 'Your curiosity dances with autumn''s mysteries — let new ideas take flight.', 'I communicate with clarity and charm.', 'The changing season mirrors your adaptable nature. Use this time to explore new interests and connect with diverse perspectives.', 'September brings mental clarity and communication breakthroughs for Gemini. Your versatile nature helps you navigate seasonal transitions.', '2025-10-14'),

('2025-09-14', 'Cancer', 'Northern', 'Nurture your dreams as autumn nurtures the earth — with gentle persistence.', 'I honor my emotions as sacred guidance.', 'Your intuitive gifts strengthen as the veil between seasons grows thin. Trust your inner knowing to guide important decisions.', 'September illuminates Cancer''s emotional wisdom. The autumn season supports deep reflection and family connections.', '2025-10-14'),

('2025-09-14', 'Leo', 'Northern', 'Your radiance warms the cooling air — shine your light on what matters most.', 'I express my authentic self with confidence.', 'Even as summer fades, your inner fire burns bright. Use your natural charisma to inspire others through seasonal transitions.', 'September allows Leo to shine with mature confidence. Your leadership skills are recognized and rewarded.', '2025-10-14'),

('2025-09-14', 'Virgo', 'Northern', 'Autumn''s precision mirrors your own — organize your life with loving attention.', 'I serve others through my dedication to excellence.', 'This is your season of harvest and refinement. Your attention to detail creates order from chaos and beauty from the mundane.', 'September is Virgo''s time to shine. Your analytical skills and practical wisdom are exactly what the world needs.', '2025-10-14'),

('2025-09-14', 'Libra', 'Northern', 'Balance autumn''s beauty with your natural grace — harmony flows through you.', 'I create beauty and balance wherever I go.', 'The autumn equinox resonates with your core nature. Use this powerful time to restore equilibrium in all areas of your life.', 'September brings Libra into perfect alignment with cosmic balance. The autumn equinox amplifies your natural harmony.', '2025-10-14'),

('2025-09-14', 'Scorpio', 'Northern', 'Autumn''s transformation mirrors your soul — embrace the depth of change.', 'I transform challenges into wisdom.', 'The season of death and rebirth speaks your language. Use this time for deep healing and powerful transformation.', 'September intensifies Scorpio''s transformative power. This is a time for profound personal growth and evolution.', '2025-10-14'),

('2025-09-14', 'Sagittarius', 'Northern', 'Autumn''s wisdom calls to your philosophical soul — explore new horizons of understanding.', 'I seek truth with an open heart and mind.', 'The changing season invites you to expand your worldview. Your quest for meaning finds new direction through autumn''s teachings.', 'September expands Sagittarius''s horizons. Your philosophical nature finds rich material in seasonal transitions.', '2025-10-14'),

('2025-09-14', 'Capricorn', 'Northern', 'Build your empire with autumn''s steady determination — success comes to those who persist.', 'I achieve my goals through disciplined action.', 'The season of preparation aligns with your natural planning abilities. Use this time to structure your path toward long-term success.', 'September supports Capricorn''s ambitious nature. Your disciplined approach yields significant progress.', '2025-10-14'),

('2025-09-14', 'Aquarius', 'Northern', 'Your innovative spirit finds inspiration in autumn''s unique beauty — create something revolutionary.', 'I contribute my unique gifts to the world.', 'The season of change resonates with your progressive nature. Your humanitarian ideals find practical expression.', 'September awakens Aquarius''s visionary potential. Your innovative ideas gain support from like-minded individuals.', '2025-10-14'),

('2025-09-14', 'Pisces', 'Northern', 'Let autumn''s mystical energy enhance your intuitive gifts — trust your inner knowing.', 'I flow with grace through all of life''s changes.', 'The thinning veil between seasons amplifies your psychic abilities. Use this heightened sensitivity to guide important decisions.', 'September deepens Pisces''s spiritual connection. Your compassionate nature attracts opportunities to heal and inspire.', '2025-10-14');

-- Pure Signs - Southern Hemisphere
INSERT INTO horoscope_cache (date, sign, hemisphere, daily_horoscope, affirmation, deeper_insight, monthly_forecast, expires_at) VALUES
('2025-09-14', 'Aries', 'Southern', 'Spring''s fire awakens within you — let your passion bloom with the season.', 'I emerge with renewed energy and purpose.', 'The awakening earth mirrors your own renewal. Your pioneering spirit finds fresh direction as nature comes alive.', 'September brings spring awakening for Aries. Your natural leadership emerges stronger after winter''s reflection.', '2025-10-14'),

('2025-09-14', 'Taurus', 'Southern', 'Spring''s abundance calls to your earthy soul — plant seeds of lasting beauty.', 'I grow with patience and natural wisdom.', 'The season of new growth aligns perfectly with your steady nature. Your practical approach creates sustainable progress.', 'September offers Taurus perfect energy for new beginnings. Your patient approach yields beautiful results.', '2025-10-14'),

('2025-09-14', 'Gemini', 'Southern', 'Spring''s curiosity matches your own — explore new ideas with childlike wonder.', 'I embrace change with adaptability and joy.', 'The season of renewal sparks your mental agility. Your communication skills help others navigate spring''s energy.', 'September energizes Gemini''s versatile nature. Spring''s dynamic energy supports new learning and connections.', '2025-10-14'),

('2025-09-14', 'Cancer', 'Southern', 'Spring''s nurturing energy flows through you — tend to what needs your care.', 'I nurture growth with loving attention.', 'The season of new life resonates with your caring nature. Your emotional intelligence guides others through change.', 'September awakens Cancer''s nurturing instincts. Spring energy supports family growth and emotional healing.', '2025-10-14'),

('2025-09-14', 'Leo', 'Southern', 'Spring''s radiance matches your inner fire — let your light guide others to growth.', 'I shine brightly as nature awakens around me.', 'The season of emergence amplifies your natural magnetism. Your creative energy finds perfect expression.', 'September illuminates Leo''s creative potential. Spring''s vibrant energy supports artistic projects and leadership.', '2025-10-14'),

('2025-09-14', 'Virgo', 'Southern', 'Spring''s precision in new growth mirrors your attention to detail — cultivate with care.', 'I serve the highest good through mindful action.', 'The season of careful cultivation aligns with your methodical nature. Your practical wisdom helps others organize renewal.', 'September supports Virgo''s desire for improvement. Spring energy enhances your ability to create order and beauty.', '2025-10-14'),

('2025-09-14', 'Libra', 'Southern', 'Spring''s balance of growth and beauty speaks to your harmonious soul.', 'I create harmony between all aspects of my life.', 'The season of equilibrium resonates with your core nature. Your diplomatic skills help others find balance.', 'September brings Libra into perfect spring alignment. Your natural ability to create harmony flourishes.', '2025-10-14'),

('2025-09-14', 'Scorpio', 'Southern', 'Spring''s transformation from winter''s depth mirrors your regenerative power.', 'I emerge transformed and empowered.', 'The season of rebirth speaks your language fluently. Your ability to transform challenges guides others through change.', 'September intensifies Scorpio''s transformative abilities. Spring''s regenerative energy supports deep healing.', '2025-10-14'),

('2025-09-14', 'Sagittarius', 'Southern', 'Spring''s expansion calls to your adventurous spirit — explore new territories of growth.', 'I seek wisdom through joyful exploration.', 'The season of growth invites you to expand your horizons. Your philosophical nature finds fresh inspiration.', 'September expands Sagittarius''s possibilities. Spring energy supports new adventures and discoveries.', '2025-10-14'),

('2025-09-14', 'Capricorn', 'Southern', 'Spring''s structured growth aligns with your ambitious nature — build with purpose.', 'I achieve lasting success through patient effort.', 'The season of methodical growth resonates with your disciplined approach. Your leadership guides sustainable progress.', 'September supports Capricorn''s long-term vision. Spring energy enhances your ability to build foundations.', '2025-10-14'),

('2025-09-14', 'Aquarius', 'Southern', 'Spring''s innovation in nature inspires your revolutionary spirit — create positive change.', 'I contribute unique solutions to collective growth.', 'The season of progressive change aligns with your visionary nature. Your humanitarian ideals find practical expression.', 'September awakens Aquarius''s innovative potential. Spring energy supports progressive projects and connections.', '2025-10-14'),

('2025-09-14', 'Pisces', 'Southern', 'Spring''s intuitive flow matches your spiritual nature — trust your inner guidance.', 'I flow with spring''s renewing energy.', 'The season of spiritual renewal amplifies your psychic gifts. Your compassionate nature helps others navigate awakening.', 'September deepens Pisces''s spiritual connection. Spring energy enhances your ability to heal and inspire.', '2025-10-14');

-- Cusp Signs - Northern Hemisphere
INSERT INTO horoscope_cache (date, sign, hemisphere, daily_horoscope, affirmation, deeper_insight, mystic_opening, monthly_forecast, expires_at) VALUES
('2025-09-14', 'Aries–Taurus Cusp', 'Northern', 'Autumn''s fire meets earth within you — create something that endures beyond seasons.', 'I embody both passion and patience.', 'Your dual nature allows you to initiate with wisdom and build with heart. The season supports sustainable progress.', 'The Cusp of Power awakens in autumn''s embrace — where Aries fire learns Taurus patience, creating unstoppable momentum.', 'September balances your fire and earth energies. Your ability to start strong and finish steady creates lasting achievements.', '2025-10-14'),

('2025-09-14', 'Taurus–Gemini Cusp', 'Northern', 'Your grounded curiosity finds autumn''s secrets — explore with both feet on the earth.', 'I blend stability with adaptability.', 'The season of change supports your versatile nature while honoring your need for security.', 'The Cusp of Energy finds perfect balance in autumn — where Taurus stability meets Gemini flexibility.', 'September enhances your ability to communicate practical wisdom. Your grounded approach creates lasting value.', '2025-10-14'),

('2025-09-14', 'Gemini–Cancer Cusp', 'Northern', 'Autumn''s emotional depth calls to your intuitive mind — let feeling guide your thoughts.', 'I think with my heart and feel with my mind.', 'The season''s emotional richness resonates with your dual nature. Your ability to communicate feelings creates connections.', 'The Cusp of Magic awakens in autumn''s mystery — where Gemini''s curiosity meets Cancer''s intuition.', 'September deepens your emotional intelligence. Your ability to articulate feelings helps others navigate transitions.', '2025-10-14'),

('2025-09-14', 'Cancer–Leo Cusp', 'Northern', 'Your nurturing fire warms autumn''s chill — lead with both heart and radiance.', 'I nurture others while honoring my own light.', 'The season supports your ability to care for others while maintaining creative expression.', 'The Cusp of Oscillation finds its rhythm in autumn — where Cancer''s depth meets Leo''s radiance.', 'September illuminates your unique leadership style. Your ability to nurture while inspiring creates positive change.', '2025-10-14'),

('2025-09-14', 'Leo–Virgo Cusp', 'Northern', 'Autumn''s precision meets your creative fire — craft something beautiful and perfect.', 'I express my creativity with meticulous care.', 'The season of refinement aligns with your dual nature. Your passion and precision yield masterful results.', 'The Cusp of Exposure shines in autumn''s light — where Leo''s creativity meets Virgo''s precision.', 'September enhances your artistic abilities. Your attention to detail combined with vision produces lasting work.', '2025-10-14'),

('2025-09-14', 'Virgo–Libra Cusp', 'Northern', 'Autumn''s beauty calls to your aesthetic soul — create harmony through careful attention.', 'I serve beauty through practical wisdom.', 'The season of balance resonates with your core nature. Your ability to create order and beauty brings peace.', 'The Cusp of Beauty flourishes in autumn — where Virgo''s precision meets Libra''s aesthetics.', 'September supports your desire to create beautiful, functional solutions that serve the highest good.', '2025-10-14'),

('2025-09-14', 'Libra–Scorpio Cusp', 'Northern', 'Autumn''s intensity meets your diplomatic grace — transform conflict into understanding.', 'I balance light and shadow with wisdom.', 'The season of transformation supports your ability to navigate emotional depths with grace and wisdom.', 'The Cusp of Drama finds its power in autumn — where Libra''s harmony meets Scorpio''s intensity.', 'September deepens your ability to create meaningful change through diplomatic transformation.', '2025-10-14'),

('2025-09-14', 'Scorpio–Sagittarius Cusp', 'Northern', 'Autumn''s truth-seeking energy ignites your revolutionary spirit — pursue what matters.', 'I seek truth with passionate dedication.', 'The season of deep change resonates with your transformative nature. Your quest for truth finds powerful expression.', 'The Cusp of Revolution awakens in autumn — where Scorpio''s depth meets Sagittarius''s vision.', 'September intensifies your ability to create meaningful change through passionate pursuit of truth.', '2025-10-14'),

('2025-09-14', 'Sagittarius–Capricorn Cusp', 'Northern', 'Autumn''s wisdom meets your visionary nature — build dreams with practical magic.', 'I manifest my visions through disciplined action.', 'The season of preparation supports your ability to turn dreams into reality through structured effort.', 'The Cusp of Prophecy finds its power in autumn — where Sagittarius''s vision meets Capricorn''s discipline.', 'September enhances your ability to manifest long-term visions through practical, sustained effort.', '2025-10-14'),

('2025-09-14', 'Capricorn–Aquarius Cusp', 'Northern', 'Autumn''s structure meets your innovative spirit — revolutionize with purpose.', 'I create lasting change through innovative discipline.', 'The season of organized change supports your unique ability to revolutionize systems with practical wisdom.', 'The Cusp of Mystery awakens in autumn — where Capricorn''s structure meets Aquarius''s innovation.', 'September supports your ability to create systematic change that serves the collective good.', '2025-10-14'),

('2025-09-14', 'Aquarius–Pisces Cusp', 'Northern', 'Autumn''s mystical energy meets your humanitarian heart — heal the world with compassion.', 'I serve humanity through intuitive wisdom.', 'The season of spiritual depth supports your ability to channel cosmic insights into practical healing.', 'The Cusp of Sensitivity awakens in autumn — where Aquarius''s vision meets Pisces''s compassion.', 'September deepens your ability to serve others through intuitive understanding and humanitarian action.', '2025-10-14'),

('2025-09-14', 'Pisces–Aries Cusp', 'Northern', 'Autumn''s mystical fire ignites your dreams — let intuition guide bold action.', 'I act on my dreams with courage and wisdom.', 'The season of transformation supports your ability to turn spiritual insights into meaningful action.', 'The Cusp of Rebirth awakens in autumn — where Pisces''s intuition meets Aries''s courage.', 'September enhances your ability to manifest dreams through inspired action and spiritual courage.', '2025-10-14');

-- Cusp Signs - Southern Hemisphere
INSERT INTO horoscope_cache (date, sign, hemisphere, daily_horoscope, affirmation, deeper_insight, mystic_opening, monthly_forecast, expires_at) VALUES
('2025-09-14', 'Aries–Taurus Cusp', 'Southern', 'Spring''s passionate earth energy flows through you — build dreams with fiery determination.', 'I create with both passion and persistence.', 'The season of renewal supports your dual nature. Your ability to start strong and build steady creates lasting success.', 'The Cusp of Power awakens in spring — where Aries fire meets Taurus earth, creating sustainable passion.', 'September energizes your ability to manifest through balanced action. Spring supports both initiative and endurance.', '2025-10-14'),

('2025-09-14', 'Taurus–Gemini Cusp', 'Southern', 'Spring''s curious abundance calls to your versatile soul — explore with grounded wisdom.', 'I adapt while staying rooted in my truth.', 'The season of growth supports your need for both stability and variety. Your practical communication creates value.', 'The Cusp of Energy flourishes in spring — where Taurus grounding meets Gemini curiosity.', 'September enhances your ability to communicate practical wisdom while exploring new possibilities.', '2025-10-14'),

('2025-09-14', 'Gemini–Cancer Cusp', 'Southern', 'Spring''s emotional awakening meets your intuitive mind — feel your way to truth.', 'I trust both my thoughts and my feelings.', 'The season of emotional renewal supports your dual nature. Your ability to think with feeling creates deep understanding.', 'The Cusp of Magic awakens in spring — where Gemini''s mind meets Cancer''s heart.', 'September deepens your emotional intelligence while enhancing your communication gifts.', '2025-10-14'),

('2025-09-14', 'Cancer–Leo Cusp', 'Southern', 'Spring''s nurturing radiance flows through you — care for others while honoring your light.', 'I lead with love and shine with compassion.', 'The season of growth supports your ability to nurture while inspiring. Your caring leadership creates positive change.', 'The Cusp of Oscillation finds balance in spring — where Cancer''s care meets Leo''s radiance.', 'September illuminates your unique ability to lead through love and inspire through authentic caring.', '2025-10-14'),

('2025-09-14', 'Leo–Virgo Cusp', 'Southern', 'Spring''s creative precision calls to your artistic soul — craft beauty with passionate detail.', 'I create with both heart and skill.', 'The season of renewal supports your dual creative nature. Your ability to express with both passion and precision yields mastery.', 'The Cusp of Exposure shines in spring — where Leo''s creativity meets Virgo''s precision.', 'September enhances your artistic abilities. Your combination of vision and skill creates works of lasting beauty.', '2025-10-14'),

('2025-09-14', 'Virgo–Libra Cusp', 'Southern', 'Spring''s harmonious growth speaks to your aesthetic soul — create beauty through service.', 'I serve the world through beauty and order.', 'The season of balanced growth aligns with your nature. Your ability to create functional beauty serves the highest good.', 'The Cusp of Beauty awakens in spring — where Virgo''s service meets Libra''s aesthetics.', 'September supports your desire to create beautiful solutions that serve both function and form.', '2025-10-14'),

('2025-09-14', 'Libra–Scorpio Cusp', 'Southern', 'Spring''s transformative beauty calls to your diplomatic intensity — create harmony from depth.', 'I transform through grace and understanding.', 'The season of renewal supports your ability to create beauty from transformation. Your diplomatic intensity heals divisions.', 'The Cusp of Drama finds its power in spring — where Libra''s harmony meets Scorpio''s transformation.', 'September enhances your ability to create meaningful change through graceful transformation.', '2025-10-14'),

('2025-09-14', 'Scorpio–Sagittarius Cusp', 'Southern', 'Spring''s revolutionary energy ignites your truth-seeking soul — pursue transformation with wisdom.', 'I seek truth through passionate exploration.', 'The season of rebirth supports your revolutionary nature. Your quest for truth finds powerful expression in renewal.', 'The Cusp of Revolution awakens in spring — where Scorpio''s transformation meets Sagittarius''s quest.', 'September intensifies your ability to create change through passionate pursuit of truth and wisdom.', '2025-10-14'),

('2025-09-14', 'Sagittarius–Capricorn Cusp', 'Southern', 'Spring''s visionary growth meets your practical wisdom — manifest dreams with earthly magic.', 'I build my visions with practical wisdom.', 'The season of structured growth supports your ability to manifest dreams through disciplined action.', 'The Cusp of Prophecy awakens in spring — where Sagittarius''s vision meets Capricorn''s discipline.', 'September enhances your ability to turn philosophical insights into practical achievements.', '2025-10-14'),

('2025-09-14', 'Capricorn–Aquarius Cusp', 'Southern', 'Spring''s innovative structure calls to your revolutionary soul — build the future with purpose.', 'I create lasting change through innovative action.', 'The season of progressive growth supports your ability to revolutionize systems with practical innovation.', 'The Cusp of Mystery awakens in spring — where Capricorn''s structure meets Aquarius''s innovation.', 'September supports your ability to create systematic change that serves collective evolution.', '2025-10-14'),

('2025-09-14', 'Aquarius–Pisces Cusp', 'Southern', 'Spring''s compassionate innovation flows through you — heal the world with visionary love.', 'I serve through intuitive innovation.', 'The season of spiritual renewal supports your ability to channel cosmic insights into humanitarian service.', 'The Cusp of Sensitivity awakens in spring — where Aquarius''s vision meets Pisces''s compassion.', 'September deepens your ability to serve humanity through intuitive wisdom and innovative compassion.', '2025-10-14'),

('2025-09-14', 'Pisces–Aries Cusp', 'Southern', 'Spring''s mystical courage ignites your dreams — let intuition guide passionate action.', 'I act on my dreams with spiritual courage.', 'The season of rebirth supports your ability to transform spiritual insights into bold, meaningful action.', 'The Cusp of Rebirth awakens in spring — where Pisces''s intuition meets Aries''s courage.', 'September enhances your ability to manifest dreams through spiritually guided action and intuitive courage.', '2025-10-14');

-- Alternative cusp name formats for better matching
INSERT INTO horoscope_cache (date, sign, hemisphere, daily_horoscope, affirmation, deeper_insight, mystic_opening, monthly_forecast, expires_at) VALUES
-- Northern Hemisphere alternative formats
('2025-09-14', 'Aries-Taurus Cusp', 'Northern', 'Autumn''s fire meets earth within you — create something that endures beyond seasons.', 'I embody both passion and patience.', 'Your dual nature allows you to initiate with wisdom and build with heart. The season supports sustainable progress.', 'The Cusp of Power awakens in autumn''s embrace — where Aries fire learns Taurus patience, creating unstoppable momentum.', 'September balances your fire and earth energies. Your ability to start strong and finish steady creates lasting achievements.', '2025-10-14'),

('2025-09-14', 'Taurus-Gemini Cusp', 'Northern', 'Your grounded curiosity finds autumn''s secrets — explore with both feet on the earth.', 'I blend stability with adaptability.', 'The season of change supports your versatile nature while honoring your need for security.', 'The Cusp of Energy finds perfect balance in autumn — where Taurus stability meets Gemini flexibility.', 'September enhances your ability to communicate practical wisdom. Your grounded approach creates lasting value.', '2025-10-14'),

('2025-09-14', 'Gemini-Cancer Cusp', 'Northern', 'Autumn''s emotional depth calls to your intuitive mind — let feeling guide your thoughts.', 'I think with my heart and feel with my mind.', 'The season''s emotional richness resonates with your dual nature. Your ability to communicate feelings creates connections.', 'The Cusp of Magic awakens in autumn''s mystery — where Gemini''s curiosity meets Cancer''s intuition.', 'September deepens your emotional intelligence. Your ability to articulate feelings helps others navigate transitions.', '2025-10-14'),

('2025-09-14', 'Cancer-Leo Cusp', 'Northern', 'Your nurturing fire warms autumn''s chill — lead with both heart and radiance.', 'I nurture others while honoring my own light.', 'The season supports your ability to care for others while maintaining creative expression.', 'The Cusp of Oscillation finds its rhythm in autumn — where Cancer''s depth meets Leo''s radiance.', 'September illuminates your unique leadership style. Your ability to nurture while inspiring creates positive change.', '2025-10-14'),

('2025-09-14', 'Leo-Virgo Cusp', 'Northern', 'Autumn''s precision meets your creative fire — craft something beautiful and perfect.', 'I express my creativity with meticulous care.', 'The season of refinement aligns with your dual nature. Your passion and precision yield masterful results.', 'The Cusp of Exposure shines in autumn''s light — where Leo''s creativity meets Virgo''s precision.', 'September enhances your artistic abilities. Your attention to detail combined with vision produces lasting work.', '2025-10-14'),

('2025-09-14', 'Virgo-Libra Cusp', 'Northern', 'Autumn''s beauty calls to your aesthetic soul — create harmony through careful attention.', 'I serve beauty through practical wisdom.', 'The season of balance resonates with your core nature. Your ability to create order and beauty brings peace.', 'The Cusp of Beauty flourishes in autumn — where Virgo''s precision meets Libra''s aesthetics.', 'September supports your desire to create beautiful, functional solutions that serve the highest good.', '2025-10-14'),

('2025-09-14', 'Libra-Scorpio Cusp', 'Northern', 'Autumn''s intensity meets your diplomatic grace — transform conflict into understanding.', 'I balance light and shadow with wisdom.', 'The season of transformation supports your ability to navigate emotional depths with grace and wisdom.', 'The Cusp of Drama finds its power in autumn — where Libra''s harmony meets Scorpio''s intensity.', 'September deepens your ability to create meaningful change through diplomatic transformation.', '2025-10-14'),

('2025-09-14', 'Scorpio-Sagittarius Cusp', 'Northern', 'Autumn''s truth-seeking energy ignites your revolutionary spirit — pursue what matters.', 'I seek truth with passionate dedication.', 'The season of deep change resonates with your transformative nature. Your quest for truth finds powerful expression.', 'The Cusp of Revolution awakens in autumn — where Scorpio''s depth meets Sagittarius''s vision.', 'September intensifies your ability to create meaningful change through passionate pursuit of truth.', '2025-10-14'),

('2025-09-14', 'Sagittarius-Capricorn Cusp', 'Northern', 'Autumn''s wisdom meets your visionary nature — build dreams with practical magic.', 'I manifest my visions through disciplined action.', 'The season of preparation supports your ability to turn dreams into reality through structured effort.', 'The Cusp of Prophecy finds its power in autumn — where Sagittarius''s vision meets Capricorn''s discipline.', 'September enhances your ability to manifest long-term visions through practical, sustained effort.', '2025-10-14'),

('2025-09-14', 'Capricorn-Aquarius Cusp', 'Northern', 'Autumn''s structure meets your innovative spirit — revolutionize with purpose.', 'I create lasting change through innovative discipline.', 'The season of organized change supports your unique ability to revolutionize systems with practical wisdom.', 'The Cusp of Mystery awakens in autumn — where Capricorn''s structure meets Aquarius''s innovation.', 'September supports your ability to create systematic change that serves the collective good.', '2025-10-14'),

('2025-09-14', 'Aquarius-Pisces Cusp', 'Northern', 'Autumn''s mystical energy meets your humanitarian heart — heal the world with compassion.', 'I serve humanity through intuitive wisdom.', 'The season of spiritual depth supports your ability to channel cosmic insights into practical healing.', 'The Cusp of Sensitivity awakens in autumn — where Aquarius''s vision meets Pisces''s compassion.', 'September deepens your ability to serve others through intuitive understanding and humanitarian action.', '2025-10-14'),

('2025-09-14', 'Pisces-Aries Cusp', 'Northern', 'Autumn''s mystical fire ignites your dreams — let intuition guide bold action.', 'I act on my dreams with courage and wisdom.', 'The season of transformation supports your ability to turn spiritual insights into meaningful action.', 'The Cusp of Rebirth awakens in autumn — where Pisces''s intuition meets Aries''s courage.', 'September enhances your ability to manifest dreams through inspired action and spiritual courage.', '2025-10-14');

-- Southern Hemisphere alternative formats
INSERT INTO horoscope_cache (date, sign, hemisphere, daily_horoscope, affirmation, deeper_insight, mystic_opening, monthly_forecast, expires_at) VALUES
('2025-09-14', 'Aries-Taurus Cusp', 'Southern', 'Spring''s passionate earth energy flows through you — build dreams with fiery determination.', 'I create with both passion and persistence.', 'The season of renewal supports your dual nature. Your ability to start strong and build steady creates lasting success.', 'The Cusp of Power awakens in spring — where Aries fire meets Taurus earth, creating sustainable passion.', 'September energizes your ability to manifest through balanced action. Spring supports both initiative and endurance.', '2025-10-14'),

('2025-09-14', 'Taurus-Gemini Cusp', 'Southern', 'Spring''s abundant curiosity calls to your grounded mind — explore with earthy wisdom.', 'I grow through both stability and exploration.', 'The season of renewal supports your need for both security and variety. Your practical communication creates lasting value.', 'The Cusp of Energy flourishes in spring — where Taurus grounding meets Gemini curiosity.', 'September enhances your ability to communicate wisdom while remaining open to new growth.', '2025-10-14'),

('2025-09-14', 'Gemini-Cancer Cusp', 'Southern', 'Spring''s emotional awakening meets your curious heart — explore feelings with wonder.', 'I embrace both thought and emotion as guides.', 'The season of emotional renewal supports your dual nature. Your ability to feel with curiosity creates deep connections.', 'The Cusp of Magic awakens in spring — where Gemini''s curiosity meets Cancer''s intuition.', 'September deepens your emotional intelligence while enhancing your natural curiosity about life.', '2025-10-14'),

('2025-09-14', 'Cancer-Leo Cusp', 'Southern', 'Spring''s nurturing fire flows through you — care for growth while shining your light.', 'I nurture with radiant love.', 'The season of growth supports your ability to care while creating. Your nurturing leadership inspires authentic growth.', 'The Cusp of Oscillation finds harmony in spring — where Cancer''s care meets Leo''s radiance.', 'September illuminates your ability to lead through love while maintaining your authentic creative expression.', '2025-10-14'),

('2025-09-14', 'Leo-Virgo Cusp', 'Southern', 'Spring''s creative order calls to your artistic precision — craft beauty with passionate detail.', 'I create with both passion and perfection.', 'The season of renewal supports your dual creative nature. Your ability to express with both fire and precision creates mastery.', 'The Cusp of Exposure shines in spring — where Leo''s creativity meets Virgo''s precision.', 'September enhances your artistic abilities. Your combination of passion and skill produces works of enduring beauty.', '2025-10-14'),

('2025-09-14', 'Virgo-Libra Cusp', 'Southern', 'Spring''s beautiful order speaks to your harmonious soul — serve through aesthetic wisdom.', 'I create beauty through loving service.', 'The season of balanced growth aligns with your nature. Your ability to serve through beauty creates harmony.', 'The Cusp of Beauty flourishes in spring — where Virgo''s service meets Libra''s aesthetics.', 'September supports your desire to create beautiful solutions that serve both individual and collective needs.', '2025-10-14'),

('2025-09-14', 'Libra-Scorpio Cusp', 'Southern', 'Spring''s transformative harmony calls to your diplomatic depth — create beauty from change.', 'I transform through grace and wisdom.', 'The season of renewal supports your ability to create harmony from transformation. Your diplomatic intensity heals and inspires.', 'The Cusp of Drama finds balance in spring — where Libra''s harmony meets Scorpio''s transformation.', 'September enhances your ability to create meaningful change through graceful, diplomatic transformation.', '2025-10-14'),

('2025-09-14', 'Scorpio-Sagittarius Cusp', 'Southern', 'Spring''s revolutionary truth ignites your transformative spirit — pursue wisdom with passion.', 'I seek truth through transformative exploration.', 'The season of rebirth supports your revolutionary nature. Your quest for truth finds powerful expression in renewal.', 'The Cusp of Revolution awakens in spring — where Scorpio''s transformation meets Sagittarius''s quest.', 'September intensifies your ability to create change through passionate pursuit of transformative truth.', '2025-10-14'),

('2025-09-14', 'Sagittarius-Capricorn Cusp', 'Southern', 'Spring''s visionary structure calls to your prophetic soul — build wisdom with practical magic.', 'I manifest wisdom through disciplined vision.', 'The season of structured growth supports your ability to manifest philosophical insights through practical action.', 'The Cusp of Prophecy awakens in spring — where Sagittarius''s vision meets Capricorn''s discipline.', 'September enhances your ability to turn spiritual insights into practical achievements that serve the greater good.', '2025-10-14'),

('2025-09-14', 'Capricorn-Aquarius Cusp', 'Southern', 'Spring''s innovative foundation calls to your revolutionary wisdom — build the future with purpose.', 'I create lasting innovation through disciplined vision.', 'The season of progressive growth supports your ability to revolutionize systems with practical innovation and wisdom.', 'The Cusp of Mystery awakens in spring — where Capricorn''s structure meets Aquarius''s innovation.', 'September supports your ability to create systematic change that honors both tradition and progress.', '2025-10-14'),

('2025-09-14', 'Aquarius-Pisces Cusp', 'Southern', 'Spring''s compassionate innovation flows through you — heal through visionary love.', 'I serve through intuitive innovation and love.', 'The season of spiritual renewal supports your ability to channel cosmic insights into compassionate service.', 'The Cusp of Sensitivity awakens in spring — where Aquarius''s vision meets Pisces''s compassion.', 'September deepens your ability to serve others through intuitive wisdom and innovative compassion.', '2025-10-14'),

('2025-09-14', 'Pisces-Aries Cusp', 'Southern', 'Spring''s mystical courage ignites your dreams — let intuition guide bold renewal.', 'I act on my dreams with spiritual courage.', 'The season of rebirth supports your ability to transform spiritual insights into bold, meaningful action.', 'The Cusp of Rebirth awakens in spring — where Pisces''s intuition meets Aries''s courage.', 'September enhances your ability to manifest dreams through spiritually guided action and intuitive courage.', '2025-10-14');